"""PDGS retrieval pipeline for experimental Fourier-plane data.

Main flow (see the numbered #%% sections at the bottom of the file):
1) Resolve dataset paths and pattern files
2) Load calibration and resolve ROI config (manual selection or saved config)
3) Build diversity phases and processed modulus stack (+ preview)
4) Run PDGS with one-shot initialization
5) Save outputs
6) Update measure_log.json

Typical user edits:
- User options block in Configuration section
- ROI selection behavior
- Visualization toggles

Notes:
- FOV selection currently uses overlay interaction.
- Signal ROI is selected on the max-alpha frame.
"""

#%% Imports
from __future__ import annotations

import json
from pathlib import Path
import re
import sys
from datetime import datetime
import numpy as np

from PIL import Image

import matplotlib.pyplot as plt
from matplotlib.widgets import RectangleSelector

# Add parent directory to path for imports (Allows the next import to work)
if __package__ is None or __package__ == "":
    sys.path.append(str(Path(__file__).resolve().parents[2]))
from python_phase_retrieval.phase_retrieval import one_shot, pdgs_log


#%% Configuration
# ---------- User-editable options ----------

# Dataset label (folder under experimental/dataset/).
measurement_label = "20260701_test_01_copy"

# Physical setup used by one_shot/PDGS propagation model.
focal_length_m = 80e-3

# PDGS settings.
nit = 2500                              # Number of PDGS iterations.
use_gpu = True                          # GPU flag.
verbose = True                          # Verbose logging for PDGS iterations (slows down execution)
progress_every = 250                    # Print progress every N iterations

# Retrieval visualization settings.
save_retrieved_plot = True              # Save retrieved phase and modulus plot as PNG
show_retrieved_plot = True              # Show retrieved phase and modulus plot interactively
save_convergence_plot = True            # Save convergence plot
show_convergence_plot = True            # Show convergence plot

# ROI selection behavior.
force_manual_selection = False
roi_config_filename = "fourier_roi_config.json"
fov_overlay_alpha = 0.8

# Experimental preprocessing: 
# Background removal on the selected signal ROI.
subtract_background = True
# Example: 20.0 means we subtract the intensity value below which 20% of ROI pixels fall.
background_percentile = 20.0

# Camera-to-model orientation alignment.
# Enable these once if camera axes are mirrored w.r.t. simulation/model convention.
# For this dataset/setup, these are the validated defaults.
camera_flip_ud = True
camera_flip_lr = False

# ---------- Internal path configuration ----------

# Resolve working directories and standard dataset/result paths.
experiment_directory = Path(__file__).resolve().parent
dataset_dir = experiment_directory / "dataset" / measurement_label
measure_log_path = dataset_dir / "measure_log.json"
patterns_dir = dataset_dir / "01_patterns_bmp"
captures_dir = dataset_dir / "02_captures_tif"
results_dir = dataset_dir / "03_results"

# Calibration capture name created by 01_generate_phases.py.
calibration_pattern_stem = "calib_rs_frame"

# Load physical parameters from measurement log generated by 01_generate_phases.py.
if not measure_log_path.exists():
    raise FileNotFoundError(
        f"Measurement log not found: {measure_log_path}. "
        "Run 01_generate_phases.py first to initialize the measurement dataset."
    )

with measure_log_path.open("r", encoding="utf-8") as f:
    measure_log = json.load(f)

generation_cfg = measure_log.get("generation")
if not isinstance(generation_cfg, dict):
    raise KeyError("Missing 'generation' section in measure_log.json")

required_generation_keys = ["slm_height", "slm_width", "pixel_pitch", "wavelength_m"]
missing_keys = [k for k in required_generation_keys if k not in generation_cfg]
if missing_keys:
    raise KeyError(f"Missing generation keys in measure_log.json: {missing_keys}")

slm_height = int(generation_cfg["slm_height"])
slm_width = int(generation_cfg["slm_width"])
pixel_pitch = float(generation_cfg["pixel_pitch"])
wavelength_m = float(generation_cfg["wavelength_m"])
flambda = wavelength_m * focal_length_m # Fresnel number parameter for PDGS propagation.


#%% Helpers

#%% ---------- Image loading and normalization ----------
_tag_re = re.compile(r"^([pm])(\d+(?:p\d+)?)e(\d+)$")


def _load_gray_image(path: Path) -> np.ndarray:
    arr = np.asarray(Image.open(path))
    if arr.ndim == 2:
        return arr
    if arr.ndim == 3:
        # Convert color to grayscale while preserving dynamic range.
        return np.mean(arr.astype(np.float64), axis=2)
    raise ValueError(f"Unsupported image shape for {path}: {arr.shape}")


def _normalize_01(arr: np.ndarray) -> np.ndarray:
    x = np.asarray(arr, dtype=np.float64)
    vmin = float(np.min(x))
    vmax = float(np.max(x))
    if np.isclose(vmax, vmin):
        return np.zeros_like(x, dtype=np.float64)
    return (x - vmin) / (vmax - vmin)


def _resize_image_to_shape(img: np.ndarray, shape_hw: tuple[int, int]) -> np.ndarray:
    h, w = shape_hw
    arr = np.asarray(np.clip(_normalize_01(img), 0.0, 1.0) * 255.0, dtype=np.uint8)
    pil_img = Image.fromarray(arr, mode="L")
    resized = pil_img.resize((w, h), resample=Image.Resampling.BICUBIC)
    return np.asarray(resized, dtype=np.float64) / 255.0


#%% ---------- Pattern/tag parsing and physical parameter helpers ----------
def _parse_tag(tag: str) -> float:
    m = _tag_re.match(tag)
    if m is None:
        raise ValueError(f"Invalid tag format: {tag}")

    sign, number, exponent = m.groups()
    value = float(number.replace("p", ".")) * (10 ** int(exponent))
    if sign == "m":
        value = -value
    return value


def _parse_sortable_tag(tag: str, digits: int = 3) -> float:
    """Parse tags produced by 01 _sortable_tag, including legacy integer mantissas.

    Legacy linear tags like p312e04 encode 3.12e04 (not 312e04).
    Newer tags with explicit decimal marker (e.g. p3p12e04) are also supported.
    """
    m = _tag_re.match(tag)
    if m is None:
        raise ValueError(f"Invalid sortable tag format: {tag}")

    sign, number, exponent = m.groups()
    if "p" in number:
        mantissa = float(number.replace("p", "."))
    else:
        # Backward-compatibility for legacy tags from _sortable_tag in 01.
        mantissa = float(number) / (10 ** (digits - 1))

    value = mantissa * (10 ** int(exponent))
    if sign == "m":
        value = -value
    return value


def _parse_pattern_params(stem: str) -> tuple[float, float, float]:
    # Expected: a_<alpha_tag>_x_<linx_tag>_y_<liny_tag>
    parts = stem.split("_")
    if len(parts) != 6 or parts[0] != "a" or parts[2] != "x" or parts[4] != "y":
        raise ValueError(f"Unexpected pattern filename stem: {stem}")

    alpha = _parse_tag(parts[1])
    linx = _parse_sortable_tag(parts[3])
    liny = _parse_sortable_tag(parts[5])
    return alpha, linx, liny


def _is_target_frame_pattern(stem: str) -> bool:
    return stem.endswith("_target_frame")


def _is_calibration_pattern(stem: str) -> bool:
    return stem == calibration_pattern_stem


def _pattern_sort_key(path: Path) -> tuple[float, float, float, str]:
    # Numeric sort by physical params; fallback to stem for deterministic tie-break.
    alpha, linx, liny = _parse_pattern_params(path.stem)
    return (alpha, linx, liny, path.stem)


def _build_phase_pdgs(
    y_m: np.ndarray,
    x_m: np.ndarray,
    alpha_rad_per_m2: float,
    beta_row: float,
    beta_col: float,
) -> np.ndarray:
    # Consistent with one_shot convention: div = (alpha/2)*r^2 + beta·x.
    quadratic = (alpha_rad_per_m2 / 2.0) * (y_m**2 + x_m**2)
    linear = beta_row * y_m + beta_col * x_m
    return quadratic + linear


#%% ---------- ROI geometry helpers ----------
def _clip_rect_to_shape(rect: tuple[int, int, int, int], shape: tuple[int, int]) -> tuple[int, int, int, int]:
    h, w = shape
    x, y, rw, rh = rect
    x = max(0, min(x, w - 1))
    y = max(0, min(y, h - 1))
    rw = max(1, min(rw, w - x))
    rh = max(1, min(rh, h - y))
    return (x, y, rw, rh)


def _adjust_rect_edges(
    rect: tuple[int, int, int, int],
    left: int,
    right: int,
    top: int,
    bottom: int,
    shape: tuple[int, int],
) -> tuple[int, int, int, int]:
    x, y, rw, rh = rect
    h, w = shape

    x0 = x + int(left)
    y0 = y + int(top)
    x1 = x + rw - 1 + int(right)
    y1 = y + rh - 1 + int(bottom)

    x0 = max(0, min(x0, w - 1))
    x1 = max(0, min(x1, w - 1))
    y0 = max(0, min(y0, h - 1))
    y1 = max(0, min(y1, h - 1))

    if x1 < x0:
        x1 = x0
    if y1 < y0:
        y1 = y0

    return (x0, y0, x1 - x0 + 1, y1 - y0 + 1)


#%% ---------- Matplotlib keymap utilities ----------
def _suspend_mpl_default_keymaps() -> dict[str, list[str]]:
    saved: dict[str, list[str]] = {}
    for key in list(plt.rcParams.keys()):
        if key.startswith("keymap."):
            value = plt.rcParams[key]
            saved[key] = list(value) if isinstance(value, list) else [str(value)]
            plt.rcParams[key] = []
    return saved


def _restore_mpl_default_keymaps(saved: dict[str, list[str]]) -> None:
    for key, value in saved.items():
        plt.rcParams[key] = value


#%% ---------- Manual ROI selection UIs ----------
def _display_preprocess(img: np.ndarray) -> np.ndarray:
    """Shared gamma + percentile-stretch used by all manual selection UIs."""
    x = img.astype(np.float64)
    x = (x - x.min()) / (x.max() - x.min() + 1e-8)
    x = np.power(x, 0.2)
    p_low, p_high = np.percentile(x, [1.0, 99.7])
    return np.clip((x - p_low) / (p_high - p_low + 1e-8), 0.0, 1.0)


def _manual_draw_rect(
    img: np.ndarray,
    title: str,
    display_cmap: str = "gray",
) -> tuple[int, int, int, int]:
    img_corrected = _display_preprocess(img)

    fig, ax = plt.subplots(figsize=(10, 8))
    ax.imshow(img_corrected, cmap=display_cmap)
    ax.set_title(
        title + "\nLeft click+drag to draw, adjust handles/drag box, ENTER to confirm, ESC to cancel"
    )

    selected_rect: dict[str, tuple[int, int, int, int]] = {}
    cancelled = {"value": False}

    def _on_select(eclick, erelease) -> None:
        if eclick.xdata is None or eclick.ydata is None:
            return
        if erelease.xdata is None or erelease.ydata is None:
            return

        x0 = int(round(min(eclick.xdata, erelease.xdata)))
        y0 = int(round(min(eclick.ydata, erelease.ydata)))
        x1 = int(round(max(eclick.xdata, erelease.xdata)))
        y1 = int(round(max(eclick.ydata, erelease.ydata)))
        selected_rect["rect"] = (x0, y0, x1 - x0 + 1, y1 - y0 + 1)

    def _on_key(event) -> None:
        key = (event.key or "").lower()
        if key in ("enter", "return"):
            if "rect" in selected_rect:
                plt.close(fig)
            else:
                print("Draw a rectangle first, then press ENTER.")
        elif key == "escape":
            cancelled["value"] = True
            plt.close(fig)

    selector = RectangleSelector(
        ax,
        _on_select,
        useblit=True,
        button=[1],
        minspanx=2,
        minspany=2,
        spancoords="pixels",
        interactive=True,
        props={"edgecolor": "red", "facecolor": "none", "linewidth": 1.0, "alpha": 1.0},
    )

    # Keep a reference alive for the full figure lifetime.
    _ = selector
    fig.canvas.mpl_connect("key_press_event", _on_key)
    plt.show()

    if cancelled["value"]:
        raise RuntimeError(f"Selection cancelled for: {title}")

    rect = selected_rect.get("rect")
    if rect is None:
        raise RuntimeError(f"Selection cancelled for: {title}")
    return rect


def _manual_draw_fov_with_target_overlay(
    camera_img: np.ndarray,
    target_img: np.ndarray,
    title: str,
    overlay_alpha: float,
) -> tuple[int, int, int, int]:
    cam = _display_preprocess(camera_img)

    # Match camera orientation for interactive overlay alignment.
    target = np.flipud(_normalize_01(target_img))
    if target.shape != cam.shape:
        target = _resize_image_to_shape(target, cam.shape)

    img_h, img_w = cam.shape
    init_size = int(round(0.7 * min(img_h, img_w)))
    init_x = max(0, (img_w - init_size) // 2)
    init_y = max(0, (img_h - init_size) // 2)

    state: dict = {
        "rect": _clip_rect_to_shape((init_x, init_y, init_size, init_size), cam.shape),
        "done": False,
        "cancelled": False,
        "active_edge": "l",
    }
    cache: dict = {"bg": None, "capturing": False}

    # ---- Figure: full-frame image, no buttons (Enter = confirm, close window = cancel) ----
    fig = plt.figure(figsize=(11, 9))
    ax = fig.add_axes([0.04, 0.05, 0.92, 0.88])
    ax.imshow(cam, cmap="gray")
    ax.set_title(
        title
        + "\nKeys: W/A/S/D select edge (top/left/bottom/right) | arrows move that edge 1px (Shift = 10px) | Enter = confirm",
        fontsize=9,
    )
    ax.set_xlim(-0.5, img_w - 0.5)
    ax.set_ylim(img_h - 0.5, -0.5)
    ax.set_autoscale_on(False)

    # Precompute the pink overlay ONCE at a capped (but high) resolution.
    # Content never changes during interaction — only its on-screen extent does,
    # so we never resize/reallocate while dragging (this is the key to fluidity).
    # Resolution only affects the one-time cost here, not per-frame drag cost,
    # so we keep it high and let matplotlib resample smoothly (bilinear) on screen.
    max_dim = 1600
    scale = min(1.0, max_dim / float(max(target.shape)))
    oh = max(1, int(round(target.shape[0] * scale)))
    ow = max(1, int(round(target.shape[1] * scale)))
    if (oh, ow) != target.shape:
        target_small = _resize_image_to_shape(target, (oh, ow))
    else:
        target_small = target
    overlay_rgba = np.zeros((oh, ow, 4), dtype=np.float64)
    overlay_rgba[..., 0] = 1.0   # pink
    overlay_rgba[..., 1] = 0.2
    overlay_rgba[..., 2] = 0.7
    overlay_rgba[..., 3] = float(overlay_alpha) * np.clip(target_small, 0.0, 1.0)

    overlay_artist = ax.imshow(overlay_rgba, interpolation="bilinear", animated=True)
    rect_artist = plt.Rectangle(
        (0, 0), 1, 1, fill=False, edgecolor="lime", linewidth=1.5, animated=True
    )
    ax.add_patch(rect_artist)
    status_text = ax.text(
        0.01, 0.01, "", transform=ax.transAxes, fontsize=9,
        color="yellow", va="bottom", animated=True,
        bbox=dict(boxstyle="round,pad=0.3", fc="black", alpha=0.55),
    )

    # ---- Blitting helpers ----
    def _blit() -> None:
        bg = cache["bg"]
        if bg is None:
            return
        fig.canvas.restore_region(bg)
        ax.draw_artist(overlay_artist)
        ax.draw_artist(rect_artist)
        ax.draw_artist(status_text)
        fig.canvas.blit(ax.bbox)

    def _on_draw(_event) -> None:
        # Recapture a CLEAN background (no dynamic artists baked in), then repaint
        # the dynamic artists on top. Hiding them + an explicit clean draw prevents
        # the initial overlay/box from staying "impressed" in the background.
        # The guard stops the explicit canvas.draw() from re-triggering this handler.
        if cache["capturing"]:
            return
        cache["capturing"] = True
        overlay_artist.set_visible(False)
        rect_artist.set_visible(False)
        status_text.set_visible(False)
        fig.canvas.draw()
        cache["bg"] = fig.canvas.copy_from_bbox(ax.bbox)
        overlay_artist.set_visible(True)
        rect_artist.set_visible(True)
        status_text.set_visible(True)
        cache["capturing"] = False
        _blit()

    edge_labels = {"t": "TOP (W)", "b": "BOTTOM (S)", "l": "LEFT (A)", "r": "RIGHT (D)"}

    def _apply_rect(rect: tuple[int, int, int, int]) -> None:
        x0, y0, rw, rh = _clip_rect_to_shape(rect, cam.shape)
        state["rect"] = (x0, y0, rw, rh)
        overlay_artist.set_extent((x0, x0 + rw, y0 + rh, y0))
        rect_artist.set_xy((x0, y0))
        rect_artist.set_width(rw)
        rect_artist.set_height(rh)
        status_text.set_text(
            f"x={x0}  y={y0}  w={rw}  h={rh}    active edge: {edge_labels[state['active_edge']]}"
        )
        _blit()

    def _on_key(event) -> None:
        key = event.key or ""
        if key in ("enter", "return"):
            state["done"] = True
            plt.close(fig)
            return
        if key == "escape":
            state["cancelled"] = True
            plt.close(fig)
            return

        base = key.split("+")[-1]

        # W/A/S/D select which edge the arrows will move.
        select = {"w": "t", "a": "l", "s": "b", "d": "r"}
        if base in select:
            state["active_edge"] = select[base]
            _apply_rect(state["rect"])
            return

        # Arrows move ONLY the currently selected edge (Shift = 10px).
        step = 10 if key.startswith("shift+") else 1
        e = state["active_edge"]
        dl = dr = dt = db = 0
        if e == "l":
            if base == "left":
                dl = -step
            elif base == "right":
                dl = step
            else:
                return
        elif e == "r":
            if base == "right":
                dr = step
            elif base == "left":
                dr = -step
            else:
                return
        elif e == "t":
            if base == "up":
                dt = -step
            elif base == "down":
                dt = step
            else:
                return
        elif e == "b":
            if base == "down":
                db = step
            elif base == "up":
                db = -step
            else:
                return
        else:
            return
        _apply_rect(_adjust_rect_edges(state["rect"], dl, dr, dt, db, cam.shape))

    fig.canvas.mpl_connect("draw_event", _on_draw)
    fig.canvas.mpl_connect("key_press_event", _on_key)

    _apply_rect(state["rect"])
    # Suspend matplotlib's built-in shortcuts so W/A/S/D (and 's' = save) don't
    # trigger default behaviour while the picker is open.
    saved_keymaps = _suspend_mpl_default_keymaps()
    try:
        plt.show()
    finally:
        _restore_mpl_default_keymaps(saved_keymaps)

    if state["cancelled"] or not state["done"]:
        raise RuntimeError(f"Selection cancelled for: {title}")

    return state["rect"]


#%% ---------- Image crop/resize helpers used in preprocessing ----------
def _crop_rect(img: np.ndarray, rect: tuple[int, int, int, int]) -> np.ndarray:
    x, y, w, h = rect
    return img[y:y + h, x:x + w]


def _resize_nearest(img: np.ndarray, target_h: int, target_w: int) -> np.ndarray:
    src_h, src_w = img.shape
    row_idx = np.linspace(0, src_h - 1, target_h).astype(int)
    col_idx = np.linspace(0, src_w - 1, target_w).astype(int)
    return img[row_idx][:, col_idx]


#%% ---------- Retrieval normalization and plotting ----------
def _normalize_field_energy(field: np.ndarray) -> np.ndarray:
    """Normalize a complex field so that sum(|field|^2) = 1."""
    u = np.asarray(field)
    energy = float(np.sum(np.abs(u) ** 2))
    if energy <= 0.0:
        raise ValueError("Field energy must be positive for normalization")
    return u / np.sqrt(energy)


def _save_convergence_metrics_plot(
    logs: list,
    out_path: Path,
    show_plot: bool,
) -> None:
    iters = np.array([entry.iteration for entry in logs], dtype=int)
    e_sc = np.array([entry.self_consistency_error for entry in logs], dtype=float)
    e_upd = np.array([entry.mean_update_norm for entry in logs], dtype=float)
    e_gt = np.array([entry.ground_truth_phase_rmse for entry in logs], dtype=float)

    has_gt = np.any(np.isfinite(e_gt))
    nrows = 3 if has_gt else 2
    fig, axes = plt.subplots(nrows, 1, figsize=(10, 3.2 * nrows), sharex=True)

    if nrows == 2:
        ax_sc, ax_upd = axes
        ax_gt = None
    else:
        ax_sc, ax_upd, ax_gt = axes

    ax_sc.plot(iters, e_sc, color="tab:blue")
    ax_sc.set_ylabel("MSE")
    ax_sc.set_title("Self-consistency error")
    ax_sc.grid(True, alpha=0.3)

    ax_upd.plot(iters, e_upd, color="tab:orange")
    ax_upd.set_ylabel("RMS")
    ax_upd.set_title("Mean update norm")
    ax_upd.grid(True, alpha=0.3)

    if has_gt and ax_gt is not None:
        ax_gt.plot(iters, e_gt, color="tab:green")
        ax_gt.set_ylabel("rad")
        ax_gt.set_title("Ground-truth phase RMSE")
        ax_gt.grid(True, alpha=0.3)
        ax_gt.set_xlabel("iteration")
    else:
        ax_upd.set_xlabel("iteration")

    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    if show_plot:
        plt.show()
    else:
        plt.close(fig)


def _save_retrieved_amplitude_phase_plot(
    beam_estimate: np.ndarray,
    out_path: Path,
    show_plot: bool,
) -> None:
    amplitude = np.abs(beam_estimate)
    phase = np.angle(beam_estimate)

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    im_amp = axes[0].imshow(amplitude, cmap="gray")
    axes[0].set_title("Retrieved Amplitude")
    axes[0].axis("off")
    fig.colorbar(im_amp, ax=axes[0], fraction=0.046, pad=0.04)

    im_phase = axes[1].imshow(phase, cmap="twilight", vmin=-np.pi, vmax=np.pi)
    axes[1].set_title("Retrieved Phase [rad]")
    axes[1].axis("off")
    fig.colorbar(im_phase, ax=axes[1], fraction=0.046, pad=0.04)

    fig.tight_layout()
    fig.savefig(out_path, dpi=150)

    if show_plot:
        plt.show()
    else:
        plt.close(fig)


# ---------- ROI config orchestration ----------
def _manual_select_roi_config(
    calib_img: np.ndarray,
    calib_target_img: np.ndarray | None,
    max_alpha_img: np.ndarray,
    max_alpha_stem: str,
    config_path: Path,
    overlay_alpha: float,
) -> dict:
    print("Manual ROI selection started")
    if calib_target_img is None:
        raise RuntimeError(
            "Calibration target TIFF is required for overlay FOV selection, "
            "but it was not found in measure_log['generation']['calibration_target_tif_path']."
        )

    fov_rect = _manual_draw_fov_with_target_overlay(
        camera_img=calib_img,
        target_img=calib_target_img,
        title="Select FOV by overlaying target frame on calibration capture",
        overlay_alpha=float(overlay_alpha),
    )
    fov_rect = _clip_rect_to_shape(fov_rect, calib_img.shape)

    fov_img_max_alpha = _crop_rect(max_alpha_img, fov_rect)

    signal_rect = _manual_draw_rect(
        fov_img_max_alpha,
        f"Select SIGNAL ROI on max-alpha frame ({max_alpha_stem})",
        display_cmap="prism",
    )
    signal_rect = _clip_rect_to_shape(signal_rect, fov_img_max_alpha.shape)

    cfg = {
        "fov_rect": list(fov_rect),
        "signal_rect_in_fov": list(signal_rect),
        "signal_roi_source_pattern_stem": max_alpha_stem,
        "fov_selection_mode": "overlay",
    }

    with config_path.open("w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2)
    print(f"Saved ROI config to: {config_path}")
    return cfg




#%% [1] Resolve dataset paths and pattern files
patterns_dir = patterns_dir.resolve()
captures_dir = captures_dir.resolve()
results_dir = results_dir.resolve()
# Create results directory if it doesn't exist.
results_dir.mkdir(parents=True, exist_ok=True)

# Get all pattern BMP files, identify calibration and diversity patterns, and sort them by parameters.
all_pattern_files = list(patterns_dir.glob("*.bmp"))
if not all_pattern_files:
    raise FileNotFoundError(f"No pattern BMP files found in {patterns_dir}")
# Filter out target frame patterns and calibration pattern, keeping only diversity patterns for processing.
pattern_files = [
    p
    for p in all_pattern_files
    if not _is_target_frame_pattern(p.stem) and not _is_calibration_pattern(p.stem)
]
# Sort diversity patterns by their encoded physical parameters (alpha, lin_x, lin_y).
pattern_files.sort(key=_pattern_sort_key)
# Check
if not pattern_files:
    raise RuntimeError("No non-calibration patterns found after filtering target-frame files.")

# Check for calibration capture existence (required for ROI selection and PDGS).
calib_capture = captures_dir / f"{calibration_pattern_stem}.tif"
if not calib_capture.exists():
    raise FileNotFoundError(
        f"Calibration capture not found: {calib_capture}. "
        "Generate/acquire calibration pattern first."
    )

#%% [2] Load calibration and resolve ROI config (manual or saved)
calib_img = _load_gray_image(calib_capture)
calib_target_img: np.ndarray | None = None
calib_target_tif_path = generation_cfg.get("calibration_target_tif_path")
if isinstance(calib_target_tif_path, str) and calib_target_tif_path.strip():
    calib_target_path = Path(calib_target_tif_path)
    if calib_target_path.exists():
        calib_target_img = _load_gray_image(calib_target_path)
        if calib_target_img.shape != calib_img.shape:
            calib_target_img = _resize_image_to_shape(calib_target_img, calib_img.shape)
    else:
        print(f"Warning: calibration target TIFF not found for overlay mode: {calib_target_path}")

# Use the capture corresponding to the highest alpha pattern for signal ROI selection.
max_alpha_pattern = max(pattern_files, key=lambda p: _parse_pattern_params(p.stem)[0])
max_alpha_capture = captures_dir / f"{max_alpha_pattern.stem}.tif"
if not max_alpha_capture.exists():
    raise FileNotFoundError(
        f"Max-alpha capture not found: {max_alpha_capture}. "
        "Acquire all diversity captures before running retrieval."
    )
max_alpha_img = _load_gray_image(max_alpha_capture)

roi_config_path = results_dir / roi_config_filename
if force_manual_selection:
    roi_cfg = _manual_select_roi_config(
        calib_img=calib_img,
        calib_target_img=calib_target_img,
        max_alpha_img=max_alpha_img,
        max_alpha_stem=max_alpha_pattern.stem,
        config_path=roi_config_path,
        overlay_alpha=fov_overlay_alpha,
    )
else:
    with roi_config_path.open("r", encoding="utf-8") as f:
        roi_cfg = json.load(f)
    print(f"Loaded ROI config from: {roi_config_path}")

fov_rect = tuple(int(v) for v in roi_cfg["fov_rect"])
signal_rect = tuple(int(v) for v in roi_cfg["signal_rect_in_fov"])


#%% [3] Build diversity phases and processed modulus stack
y_m_1d = (np.arange(slm_height, dtype=float) - (slm_height - 1) / 2.0) * pixel_pitch
x_m_1d = (np.arange(slm_width, dtype=float) - (slm_width - 1) / 2.0) * pixel_pitch
lattice = (y_m_1d, x_m_1d)
y_m, x_m = np.meshgrid(y_m_1d, x_m_1d, indexing="ij")

imgs_modulus: list[np.ndarray] = []
div_phases: list[np.ndarray] = []
imgs_intensity: list[np.ndarray] = []
pattern_params: list[tuple[float, float, float]] = []
pattern_params_physical: list[tuple[float, float, float]] = []

print(
    "Camera flips (ud, lr): "
    f"({camera_flip_ud}, {camera_flip_lr})"
)

for pattern_path in pattern_files:
    capture_path = captures_dir / f"{pattern_path.stem}.tif"
    if not capture_path.exists():
        raise FileNotFoundError(f"Missing capture for pattern {pattern_path.name}: {capture_path}")

    alpha_phys, linx_phys, liny_phys = _parse_pattern_params(pattern_path.stem)
    # lattice_dot(beta, lattice) follows (row, col) order => (y, x) in SI units.
    beta_row = 2.0 * np.pi * float(liny_phys)
    beta_col = 2.0 * np.pi * float(linx_phys)
    div_phase = _build_phase_pdgs(
        y_m=y_m,
        x_m=x_m,
        alpha_rad_per_m2=alpha_phys,
        beta_row=beta_row,
        beta_col=beta_col,
    )

    raw_img = _load_gray_image(capture_path)
    fov_img = _crop_rect(raw_img, fov_rect)

    # Keep only selected signal ROI first.
    mask = np.zeros(fov_img.shape, dtype=np.float64)
    sx, sy, sw, sh = signal_rect
    mask[sy:sy + sh, sx:sx + sw] = 1.0

    masked_fov = fov_img.astype(np.float64) * mask

    # Background correction is applied only inside the selected ROI mask.
    # We estimate a scalar pedestal from masked pixels, then subtract it from
    # masked_fov (and clamp negatives to zero).
    if subtract_background:
        signal_pixels = masked_fov[mask > 0.0]
        if signal_pixels.size > 0:
            bg_level = float(np.percentile(signal_pixels, background_percentile))
            masked_fov = np.clip(masked_fov - bg_level * mask, 0.0, None)

    if camera_flip_ud:
        masked_fov = np.flipud(masked_fov)
    if camera_flip_lr:
        masked_fov = np.fliplr(masked_fov)

    resized_img = _resize_nearest(masked_fov, slm_height, slm_width)

    intensity = np.clip(resized_img.astype(np.float64), 0.0, None)
    intensity_sum = float(np.sum(intensity))
    if intensity_sum <= 0.0:
        raise ValueError(f"Zero-energy processed frame for pattern {pattern_path.stem}")
    intensity = intensity / intensity_sum

    imgs_intensity.append(intensity)
    imgs_modulus.append(np.sqrt(intensity))
    div_phases.append(div_phase)
    pattern_params.append((alpha_phys, beta_row, beta_col))
    pattern_params_physical.append((alpha_phys, linx_phys, liny_phys))

if not imgs_modulus:
    raise RuntimeError("No non-calibration patterns found for PDGS.")


#%% [3b] Preview processed modulus stack before PDGS
print(f"Generated dataset: {len(imgs_modulus)} frames, shape: {imgs_modulus[0].shape}")

n_show = min(len(imgs_modulus), 10)
nrows = 2
ncols = int(np.ceil(n_show / nrows))
fig, axes = plt.subplots(nrows, ncols, figsize=(4 * ncols, 4 * nrows))
axes = np.atleast_1d(axes).ravel()
for idx in range(n_show):
    alpha_millions = pattern_params_physical[idx][0] / 1e6
    axes[idx].imshow(imgs_modulus[idx], cmap="gray")
    axes[idx].set_title(f"|u| #{idx + 1}\nalpha={alpha_millions:g}e6")
    axes[idx].axis("off")
for idx in range(n_show, len(axes)):
    axes[idx].axis("off")
fig.tight_layout()
plt.show()


#%% [4] Run PDGS (one-shot init)

# Match simulation setup: initialize from one-shot using the last diversity image.
alpha_guess, beta_row_guess, beta_col_guess = pattern_params[-1]
beam_guess = one_shot(
    img_intensity=imgs_intensity[-1],
    alpha=alpha_guess,
    beta=(beta_row_guess, beta_col_guess),
    L=lattice,
    flambda=flambda,
)
beam_guess = _normalize_field_energy(beam_guess)

beam_est, logs = pdgs_log(
    imgs_modulus=imgs_modulus,
    div_phases=div_phases,
    nit=nit,
    beam_guess=beam_guess,
    L=lattice,
    flambda=flambda,
    verbose=verbose,
    progress_every=progress_every,
    use_gpu=use_gpu,
)
beam_est = _normalize_field_energy(beam_est)

if save_convergence_plot:
    _save_convergence_metrics_plot(
        logs=logs,
        out_path=results_dir / "convergence_metrics.png",
        show_plot=show_convergence_plot,
    )


#%% [5] Save outputs  →  artefatti numerici e plot in 03_results/
np.save(results_dir / "beam_estimate_complex.npy", beam_est)
np.save(results_dir / "phase_estimate_rad.npy", np.angle(beam_est))

if save_retrieved_plot:
    _save_retrieved_amplitude_phase_plot(
        beam_estimate=beam_est,
        out_path=results_dir / "retrieved_amplitude_phase.png",
        show_plot=show_retrieved_plot,
    )

with (results_dir / "pdgs_logs.json").open("w", encoding="utf-8") as f:
    json.dump([entry.__dict__ for entry in logs], f, indent=2)

run_summary = {
    "patterns_dir": str(patterns_dir),
    "captures_dir": str(captures_dir),
    "results_dir": str(results_dir),
    "calibration_pattern_stem": calibration_pattern_stem,
    "slm_height": slm_height,
    "slm_width": slm_width,
    "pixel_pitch": pixel_pitch,
    "nit": nit,
    "flambda": flambda,
    "use_gpu": use_gpu,
    "beam_guess_method": "one_shot",
    "beam_guess_alpha": float(alpha_guess),
    "beam_guess_beta": [float(beta_row_guess), float(beta_col_guess)],
    "beam_guess_params_units": "SI",
    "wavelength_m": wavelength_m,
    "focal_length_m": focal_length_m,
    "beam_guess_source_pattern_params_physical": {
        "alpha_rad_per_m2": float(pattern_params_physical[-1][0]),
        "lin_x_cpm": float(pattern_params_physical[-1][1]),
        "lin_y_cpm": float(pattern_params_physical[-1][2]),
    },
    "center_signal_order": False,
    "camera_flip_ud": bool(camera_flip_ud),
    "camera_flip_lr": bool(camera_flip_lr),
    "subtract_background": subtract_background,
    "background_percentile": background_percentile,
    "roi_config_path": str(roi_config_path),
    "signal_roi_source_pattern_stem": roi_cfg.get("signal_roi_source_pattern_stem", ""),
    "processed_pattern_stems": [p.stem for p in pattern_files],
    "processed_pattern_params_physical": [
        {
            "alpha_rad_per_m2": float(alpha),
            "lin_x_cpm": float(linx),
            "lin_y_cpm": float(liny),
        }
        for alpha, linx, liny in pattern_params_physical
    ],
}

with (results_dir / "processing_run_summary.json").open("w", encoding="utf-8") as f:
    json.dump(run_summary, f, indent=2)


#%% [6] Update measurement log  →  metadati retrieval scritti in measure_log.json (non in 03_results)
measure_log["measurement_label"] = measurement_label
measure_log["dataset_dir"] = str(dataset_dir)
measure_log["retrieval"] = {
    "nit": int(nit),
    "flambda": float(flambda),
    "use_gpu": bool(use_gpu),
    "verbose": bool(verbose),
    "progress_every": int(progress_every),
    "focal_length_m": float(focal_length_m),
    "center_signal_order": False,
    "camera_flip_ud": bool(camera_flip_ud),
    "camera_flip_lr": bool(camera_flip_lr),
    "subtract_background": bool(subtract_background),
    "background_percentile": float(background_percentile),
    "roi": {
        "fov_rect": [int(v) for v in fov_rect],
        "signal_rect_in_fov": [int(v) for v in signal_rect],
        "fov_selection_mode": "overlay",
        "signal_roi_source_pattern_stem": str(roi_cfg.get("signal_roi_source_pattern_stem", "")),
        "roi_config_path": str(roi_config_path),
    },
    "outputs": {
        "beam_estimate_complex_npy": str(results_dir / "beam_estimate_complex.npy"),
        "phase_estimate_rad_npy": str(results_dir / "phase_estimate_rad.npy"),
        "retrieved_amplitude_phase_png": str(results_dir / "retrieved_amplitude_phase.png"),
        "convergence_metrics_png": str(results_dir / "convergence_metrics.png"),
        "pdgs_logs_json": str(results_dir / "pdgs_logs.json"),
        "processing_run_summary_json": str(results_dir / "processing_run_summary.json"),
    },
    "processed_pattern_stems": [p.stem for p in pattern_files],
    "updated_at": datetime.now().isoformat(timespec="seconds"),
}

with measure_log_path.open("w", encoding="utf-8") as f:
    json.dump(measure_log, f, indent=2)

print(f"PDGS completed. Results in: {results_dir}")
